language: python
sudo: required
script: sudo apt update && sudo apt install python-tk python3-tk tk8.6-dev && sudo pip install pillow matplotlib numpy pyinstaller && pyinstaller -F --hidden-import tkinter --hidden-import matplotlib.backends.backend_tkagg --hidden-import packaging.specifiers --hidden-import packaging.requirements --hidden-import numpy.random.common --hidden-import numpy.random.bounded_integers --hidden-import numpy.random.entropy tiaoyitiao.py
after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
branches:
  only:
     master
env:
  global:
 
