language: python
sudo: required
brfore_install: sudo pip install pillow matplotlib numpy
script: pyinstaller -F --hidden-import packaging.specifiers --hidden-import packaging.requirements --hidden-import numpy.random.common --hidden-import numpy.random.bounded_integers --hidden-import numpy.random.entropy tiaoyitiao.py
