language: python
sudo: required
script: sudo pip install pillow matplotlib numpy && pyinstaller -F --hidden-import packaging.specifiers --hidden-import packaging.requirements --hidden-import numpy.random.common --hidden-import numpy.random.bounded_integers --hidden-import numpy.random.entropy tiaoyitiao.py
